### ISSUE TITLE
Wrong Documentation on README.md

### ISSUE THREAD

**Issue by jackcsk** [bitliner/google-translate-api-nodejs-client#1]
For your information, the example on README.md has a wrong parameter.
'q' shall be 'text' instead as referring to source code.

So it shall be:

var GoogleTranslateApi=require('google-translate-api-nodejs-client');

new GoogleTranslateApi({
  API_KEY:'...'
})
  .translate({
    source:'en',
    target:'ge',
    text:'...text is here...'
  }, function(err,translation){

```
// translation is a string representing the output translation
// original response would be in html, this client converts the html to a proper text string    
```

  });

**Comment by bitliner** [comment]
Thank you for letting know about this issue.

Feel free to do a pull request (or soon I will fix it), and  to star this repository if you like this library.

**Comment by jackcsk** [comment]
Thx @bitliner. I've just submitted the minor change.
